library/diary/urls.py
from django.urls import path
from django.views.decorators.csrf import csrf_exempt
from .views import *

app_name = 'diary'

urlpatterns = [
    path('', DiaryHome.as_view(), name='diary/index'),
    path('log/<blog_id>', csrf_exempt(DiaryLogEntryView.as_view()), name='diary/log'),
    path('about/', About.as_view(), name='home/index'),
    path('contact/', Contact.as_view(), name='contact/index'),
    path('interests/', Minigame.as_view(), name='interests/index'),
    # path('address/get', csrf_exempt(GetAddress.as_view()), name='index'),
]

miniblog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('library.diary.urls', namespace='diary')),
    path('admin/', admin.site.urls),
]

library/diary/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class BlogPost(models.Model):
    BLOG_TYPE =( 
        ("TECH", "Technology"),
        ("GAME", "Games"),
        ("INTR", "Interests"),
        ("RAND", "Random Things"),
    )

    blog_title = models.CharField(max_length=255)
    blog_created_date = models.DateTimeField(auto_now_add=True)
    blog_content = RichTextField()
    blog_type = models.CharField(max_length=255, choices=BLOG_TYPE)

    def __str__(self):
        return self.blog_title

library/diary/views.py
from django.shortcuts import render_to_response, render, redirect
from django.http import HttpResponse
from django.views.generic import View

from .models import BlogPost
# Create your views here.

class About(View):

    def get(self, request):
        return render(request, 'about.html', status=200)


class DiaryHome(View):

    def get(self, request):
        blogs = BlogPost.objects.all()
        return render(request, 'diary.html', context={'blogs': blogs})


class DiaryLogEntryView(View):

    def get(self, request, blog_id):
        blogs = BlogPost.objects.get(pk=blog_id)
        print(blogs)
        return render(request, 'diary-entry.html', context={'blogs': blogs})


class Contact(View):

    def get(self, request):
        return render(request, 'contact.html', status=200)


class Minigame(View):

    def get(self, request):
        return render(request, 'game-demo.html', status=200)

library/diary/templates/about.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="column column-80 column-offset-10">
    <div class="blog-div">
        <p class="text-center">Currently using this to document my self development progress with different tech stacks. The content mostly will be tech related, but other interest will come right after i build a base.</p>
        <hr>
    </div>
</div>
<div class="column column-10"></div>
{% endblock content %}

library/diary/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script data-ad-client="pub-6653702767404141" async src="https://pagead2.googlesyndication.com/
pagead/js/adsbygoogle.js"></script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>@carljshra | a blog app</title>

    <link href="{% static 'css/normalize.css' %}" rel="stylesheet">
    <link href="{% static 'css/milligram.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">

    <script src="{% static 'js/jquery.min.js' %}"></script>

</head>

<body>
    <div class="container">
        <div class="row">
            <div class="column column-15">
            </div>
            <div class="column column-75">
                <div class="navbar">
                    <ul>
                        <li><a href="{% url 'diary:diary/index' %}">Log</a></li>
                        <li><a class="active" href="{% url 'diary:home/index' %}">About</a></li>
                        <li><a href="{% url 'diary:contact/index' %}">Contact</a></li>
                        <li><a href="{% url 'diary:interests/index' %}">Interests</a></li>
                    </ul>
                </div>
                {% block content %}

                {% endblock %}
                
                <footer class="footer">
                    <h6 style="margin-bottom: 0.8rem !important;">
                    Designed with ♥ by
                    <a
                        target="_blank"
                        href="https://github.com/angryiceking"
                        title="Carl Almayda"
                        >Carl Almayda</a
                    >. Using 
                    <a
                        target="_blank"
                        href="https://github.com/milligram/milligram#license"
                        title="MIT License"
                        >Milligram</a
                    > Framework.
                    </h6>
                </footer>
            </div>
            <div class="column column-15">
            </div>
        </div>
    </div>
</body>

</html>

library/diary/templates/contact.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="column column-80 column-offset-10">
    <div class="blog-div">
        <div class="row">
            <div class="column column-40"></div>
            <div class="column column-20">
                <br />
                <div class="image-cropper">
                    <img src="{% static 'images/social-profile-pic.jpg' %}" class="rounded" />
                </div>
            </div>
            <div class="column column-40"></div>
        </div>
        <div class="row">
            <div class="column column-20"></div>
            <div class="column column-60">
                <br />
                <br />
                <h4 class="text-center"><b>Carl Almayda</b> | Software Engineer <br/> 
                    <small style="font-size: 60% !important;">+639208036605  | c.almayda09@gmail.com</small><br/>
                    <small style="font-size: 60% !important;"><a href="https://github.com/angryiceking">github</a> || <a href="https://www.facebook.com/carljshra">facebook</a> || <a href="https://www.linkedin.com/in/carljshra/">linkedin</a> </small>
                </h4>
            </div>
            <div class="column column-20"></div>
        </div>
        <div class="row">
            <div class="column column-10"></div>
            <div class="column column-80">
                <br />
                <p class="text-center">Currently working as a Software Engineer, managing software support,
                    automation and infrastructure of the current assigned project. Always looking
                    for improvement and is greatly motivated and compassionate in what we do
                    in industry. Greatest strength always comes from being an individual always
                    seeking for a better solution, Can vouch on self for being a hard working
                    individual.</p>
                <br />
            </div>
            <div class="column column-10"></div>
        </div>
        <div class="row">
            <div class="column column-10"></div>
            <div class="column column-80">
                <br />
                <h4 class="text-center">Features</h4>
                <ul>
                    <li>Excellent in creating web applications from scratch, do you have any idea in mind? do you wanna take it to reality? Let me hear it. :D</li>
                    <li>Excellent in producing automated processes. Want something automated? let's do it!</li>
                    <li>Best at coding things! Python numbawan! also used PHP (:poop:) but anything can be learned ain't it??</li>
                    <li>Best at managing web development servers and also production servers! apache, nginx, gunicorn.. you name it, can we agree that devops are cool?!?</li>
                    <li>Experienced how Telco system works! and how to communicate with other teams for each other's benefit.</li>
                    <li>Best at creating processes for system health detection. Never have I ever not sleep to check platform status? Not anymore :)</li>
                    <li>Please hire me. I'm a hardworking glasses boi that likes to challenge himself. Mwuhehe</li>
                </ul>
                <br />
            </div>
            <div class="column column-10"></div>
        </div>
        <div class="row">
            <div class="column column-10"></div>
            <div class="column column-80">
                <h4 class="text-center">Experiences</h4>
                <h5><b>SENIOR SOFTWARE ENGINEER</b><br/> 
                    <small>ALAB PH | <i>November 2020 - Present</i></small>
                </h5>
                <p>Started a small startup company that caters software services and automation. We're open for commissions!</p>
                <br />

                <h5><b>SUPPORT SOFTWARE ENGINEER</b><br/> 
                    <small>INFOSHIFT INCORPORATED | <i>August 2018 - Current</i></small>
                </h5>
                <p>Worked as a support slash software engineer in a startup company that caters a nationwide service about SMS Messaging</p>
                <br />

                <h5><b>APPLICATION DEVELOPER </b><br/> 
                    <small>TEAM PACIFIC CORPORATION - MIS| <i>June 2017 - August 2018</i></small>
                </h5>
                <p>I worked as a member of MIS team serving the internal network and application of the company, mainly used a self-created framework in PHP and deals with Using Oracle as database. Learned to stand on own two feet by creating solutions for standardization for the team to use.</p>
                <br />

                <h5><b>SOFTWARE ENGINEER INTERN </b><br/> 
                    <small>SAVE22 INC. | <i>August 2016 - March 2017</i></small>
                </h5>
                <p>Worked as an Intern in a company that utilizes web scraping for their product, first used python and scrapy and learned the better OS than windows.</p>
                <br />
            </div>
            <div class="column column-10"></div>
        </div>
        <div class="row">
            <div class="column column-10"></div>
            <div class="column column-80">
                <h4 class="text-center">Sample Works</h4>
                <p>Wanna have a blog site like this? feel free to fork my repo at <a href="#">github</a> and please leave a message!</p>
                <p>Coming soon!</p>
                <br />
            </div>
            <div class="column column-10"></div>
        </div>
        <hr>
    </div>
</div>
<div class="column column-10"></div>
{% endblock content %}

library/diary/templates/diary-entry.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="column column-80 column-offset-10">
    <br />
    <div class="blog-div">
        <h5><b>{{ blogs.blog_title }}</b> <br/> <small>{{ blogs.blog_created_date}}</small></h5>
        {% autoescape off %}
        <p>{{ blogs.blog_content}}</p>
        {% endautoescape %}
        <hr>
    </div>
</div>
<div class="column column-10"></div>
{% endblock content %}

library/diary/templates/diary.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="column column-80 column-offset-10">
    <br/>
    {% for blog in blogs %}
    <div class="blog-div">
        <h5><b><a href="{% url 'diary:diary/log' blog_id=blog.id %}">{{ blog.blog_title }}</a></b> | <small>{{ blog.blog_created_date}}</small> <span style="font-size: 1.2rem !important;"> {{ blog.get_blog_type_display }}</span></h5>
        {% autoescape off %}
        <div class="blog-preview-content" style="margin-top: -40px !important;">
            <p>{{ blog.blog_content}}</p>
            {% endautoescape %}
        </div>
        <hr style="margin: 0.5rem 0 !important;">
    </div>
    {% endfor %}
</div>
<div class="column column-10"></div>
{% endblock content %}

library/diary/templates/game-demo.html
{% extends 'base/base.html' %}
{% load static %}
{% block content %}
<div class="column column-80 column-offset-10">
    <div class="blog-div">
        <h4>Coming soon!</h4>
        <p>Tech</p>
        <ul>
            <li>Programming</li>
            <li>Automation</li>
            <li>Scripting</li>
            <li>Server Monitoring and Management</li>
            <li>Services Integration</li>
            <li>API Implementation</li>
            <li>Services Containerization</li>
        </ul>
        <p>Others</p>
        <ul>
            <li>Playing Games!
                <ul>
                    <li>Dota 2</li>
                    <li>Honkai Impact 3 (SEA)</li>
                    <li>Genshin Impact</li>
                    <li>Console Games (PS4) - Adventure and Puzzle games</li>
                </ul>
            </li>
            <li>Foodie</li>
            <li>Watching movies! (marvel / dc fan)</li>
            <li>Watching Anime!!</li>
        </ul>
        <hr>
    </div>
</div>
<div class="column column-10"></div>
{% endblock content %}